__author__ = 'Robert'
from AbstractDetector import AbstractDetector
from MorphologyTransformDetector import MorphologyTransformDetector
from ThresholdBlurDetector import ThresholdBlurDetector
from CannyDetector import CannyDetector